GET http://localhost:3000/api/exercise/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdUBnbWFpbC5jb20iLCJ1c2VySWQiOiI2NDJmY2NhZmQ1ODMyMWM2ZGE3OTEzYzciLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjgwOTY5MjUxLCJleHAiOjE2ODA5NzI4NTF9.SYi1XjDm1AOKzAFditlqOrD4iwBHCnYBnRqw8yL7C70

###
GET http://localhost:3000/api/exercise/public
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDNhZWI4MjI0YTE3NTg4Yjc4OGRjY2YiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjgxNjU1NTU2LCJleHAiOjE2ODE2NTkxNTZ9.4kMgvP9iorz-7TWzjRgSz5Z-PgVw9LxJhoblVpitlR8

###
GET http://localhost:3000/api/exercise/private
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJmY2NhZmQ1ODMyMWM2ZGE3OTEzYzciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODE1Nzc1MzUsImV4cCI6MTY4MTU4MTEzNX0.6IzF9DhP9mHQSvYEfd1Xicnz0m94h7ZkilFPwAAGjh0

###
GET http://localhost:3000/api/exercise/for-set/true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDRlNTdiZjA5ZjkwNGI3ZTZkNmQ4YzciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODQ0MTI4MDUsImV4cCI6MTY4NDQxNjQwNX0.c3aSl1_VIlu0T9FRBfiJS13ZmOR9w-JhArIjI7AzsfQ

###
GET http://localhost:3000/api/exercise/subscriptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJmY2NhZmQ1ODMyMWM2ZGE3OTEzYzciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODE1Nzc1MzUsImV4cCI6MTY4MTU4MTEzNX0.6IzF9DhP9mHQSvYEfd1Xicnz0m94h7ZkilFPwAAGjh0

###
GET http://localhost:3000/api/exercise/6431909069e68fca4764189f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJmY2NhZmQ1ODMyMWM2ZGE3OTEzYzciLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjgxMDQ3Mjc3LCJleHAiOjE2ODEwNTA4Nzd9._uywmU9kZ0fNbL4jk9PjzKx5YU3wBL3C80_3wlMHtso

###
POST http://localhost:3000/api/exercise/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJmY2NhZmQ1ODMyMWM2ZGE3OTEzYzciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODExMzkwMzgsImV4cCI6MTY4MTE0MjYzOH0.yASDWZ6wIGQjmaFP-fqD8Apvil64OsJT3ANV5AuPPOo
Content-Type: application/json

{
  "name": "Abdominals",
  "description": "asgfhdsjgfkdhgfdjdsj",
  "image": "asgdsag.png",
  "finished_xp": 5
}