GET http://localhost:3000/api/exercise/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdUBnbWFpbC5jb20iLCJ1c2VySWQiOiI2NDJmY2NhZmQ1ODMyMWM2ZGE3OTEzYzciLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjgwOTY5MjUxLCJleHAiOjE2ODA5NzI4NTF9.SYi1XjDm1AOKzAFditlqOrD4iwBHCnYBnRqw8yL7C70

###
GET http://localhost:3000/api/exercise/public
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdUBnbWFpbC5jb20iLCJ1c2VySWQiOiI2NDJmY2NhZmQ1ODMyMWM2ZGE3OTEzYzciLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjgwOTY5MjUxLCJleHAiOjE2ODA5NzI4NTF9.SYi1XjDm1AOKzAFditlqOrD4iwBHCnYBnRqw8yL7C70

###
GET http://localhost:3000/api/exercise/private
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdUBnbWFpbC5jb20iLCJ1c2VySWQiOiI2NDJmY2NhZmQ1ODMyMWM2ZGE3OTEzYzciLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjgwOTY5MjUxLCJleHAiOjE2ODA5NzI4NTF9.SYi1XjDm1AOKzAFditlqOrD4iwBHCnYBnRqw8yL7C70

###
GET http://localhost:3000/api/exercise/6431909069e68fca4764189f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJmY2NhZmQ1ODMyMWM2ZGE3OTEzYzciLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjgxMDQ3Mjc3LCJleHAiOjE2ODEwNTA4Nzd9._uywmU9kZ0fNbL4jk9PjzKx5YU3wBL3C80_3wlMHtso

###
POST http://localhost:3000/api/exercise/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDJmY2NhZmQ1ODMyMWM2ZGE3OTEzYzciLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2ODExMzkwMzgsImV4cCI6MTY4MTE0MjYzOH0.yASDWZ6wIGQjmaFP-fqD8Apvil64OsJT3ANV5AuPPOo
Content-Type: application/json

{
  "name": "Abdominals",
  "description": "asgfhdsjgfkdhgfdjdsj",
  "image": "asgdsag.png",
  "finished_xp": 5
}